#Fake News Detection

## Assignment 1

Here are some assignment problems to practice the concepts that we discussed in the class. The problems have necessary starting code.

### Problem 1: Word Count Ignoring Punctuation (Built-in Functions)

**Task:** Write a Python function that counts the number of words in a given string, ignoring all punctuation. Only consider sequences of alphanumeric characters as words. You should only use Python's built-in string methods (no regex or NLP libraries).

In [ ]:
text = "Hello, world! How are you doing today? Let's count these words (properly)."

def word_count(text):
    # Replace punctuation with space, then split
    cleaned = ""
    for char in text:
        if char.isalnum() or char == " ":
            cleaned += char
        else:
            cleaned += " "
    words = [w for w in cleaned.split() if w]
    return len(words)

print(word_count(text))

13


### Problem 2: Extracting URLs (Regex)

**Task:** Use regular expressions to find and extract all URLs (web addresses starting with `http://` or `https://`) from a given text.

In [ ]:
import re

text = "Visit Google at https://www.google.com or check out Wikipedia at http://en.wikipedia.org for more info. My site is example.com"

urls = re.findall(r'https?://[^\s]+', text)
print(urls)


['https://www.google.com', 'http://en.wikipedia.org']


### Problem 3: NLTK Tokenization and Lowercasing

**Task:** Using NLTK, tokenize the given sentence into words and then convert all tokens to lowercase. Print the list of lowercase tokens.

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')

text = "NLTK Is a powerful Library for Natural Language Processing."

tokens = word_tokenize(text)
lowercase_tokens = [token.lower() for token in tokens]
print(lowercase_tokens)


['nltk', 'is', 'a', 'powerful', 'library', 'for', 'natural', 'language', 'processing', '.']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


### Problem 4: Stemming a List of Words (NLTK PorterStemmer)

**Task:** Apply NLTK's `PorterStemmer` to a list of words and print the stemmed versions of each word.

In [ ]:
import nltk
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()
words = ["running", "runs", "runner", "easily", "fairly", "universal", "universities"]

stemmed = [stemmer.stem(word) for word in words]
for original, stem in zip(words, stemmed):
    print(f"{original} --> {stem}")


running --> run
runs --> run
runner --> runner
easily --> easili
fairly --> fairli
universal --> univers
universities --> univers


### Problem 5: Lemmatization with spaCy

**Task:** Use spaCy to lemmatize each word in the provided sentence. Print each word along with its lemma.

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")
text = "The quick brown foxes are jumping over the lazy dogs and playing."

doc = nlp(text)
for token in doc:
    print(f"{token.text:15} --> {token.lemma_}")


The             --> the
quick           --> quick
brown           --> brown
foxes           --> fox
are             --> be
jumping         --> jump
over            --> over
the             --> the
lazy            --> lazy
dogs            --> dog
and             --> and
playing         --> playing
.               --> .


### Problem 6: Part-of-Speech Tagging with spaCy

**Task:** Process the given sentence with spaCy and print each token along with its Part-of-Speech (POS) tag.

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")
text = "Apple is looking at buying U.K. startup for $1 billion in London."

doc = nlp(text)
for token in doc:
    print(f"{token.text:12} | POS: {token.pos_:10} | Tag: {token.tag_}")

Apple        | POS: PROPN      | Tag: NNP
is           | POS: AUX        | Tag: VBZ
looking      | POS: VERB       | Tag: VBG
at           | POS: ADP        | Tag: IN
buying       | POS: VERB       | Tag: VBG
U.K.         | POS: PROPN      | Tag: NNP
startup      | POS: VERB       | Tag: VBD
for          | POS: ADP        | Tag: IN
$            | POS: SYM        | Tag: $
1            | POS: NUM        | Tag: CD
billion      | POS: NUM        | Tag: CD
in           | POS: ADP        | Tag: IN
London       | POS: PROPN      | Tag: NNP
.            | POS: PUNCT      | Tag: .


### Problem 7: Named Entity Recognition with spaCy

**Task:** Use spaCy to identify and print all named entities (e.g., persons, organizations, locations) from the text. For each entity, print its text and its label.

In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")
text = "Google was founded by Larry Page and Sergey Brin in California in 1998."

doc = nlp(text)
for ent in doc.ents:
    print(f"{ent.text:20} --> {ent.label_}")


Google               --> ORG
Larry Page           --> PERSON
Sergey Brin          --> PERSON
California           --> GPE
1998                 --> DATE


### Problem 8: Top N Most Common Words (Counter)

**Task:** Find and print the 5 most common words in the provided text. Ensure that words are lowercased and punctuation is removed before counting. Use `collections.Counter`.

In [ ]:
from collections import Counter
import re

text = "This is a sample text. This text is just a sample for demonstration purposes. Sample text is good."

words = re.findall(r'[a-z]+', text.lower())
counter = Counter(words)
print(counter.most_common(5))


[('is', 3), ('sample', 3), ('text', 3), ('this', 2), ('a', 2)]


### Problem 9: Custom Stop Word Removal

**Task:** Create a function that removes a predefined list of stop words from a given sentence. The function should return the cleaned sentence as a string.

In [13]:
stop_words = ["is", "a", "the", "and", "with", "some"]
sentence = "This is a sample sentence with some stop words that need to be removed."

def remove_stop_words(sentence, stop_words):
    words = sentence.split()
    filtered = [w for w in words if w.lower() not in stop_words]
    return " ".join(filtered)

print(remove_stop_words(sentence, stop_words))


This sample sentence stop words that need to be removed.


### Problem 10: Character Frequency Analysis (Counter)

**Task:** Calculate and print the frequency of each character (case-insensitive) in a given string using `collections.Counter`.

In [14]:
from collections import Counter

text = "Programming is Fun"

freq = Counter(text.lower())
for char, count in sorted(freq.items()):
    print(f"'{char}': {count}")

' ': 2
'a': 1
'f': 1
'g': 2
'i': 2
'm': 2
'n': 2
'o': 1
'p': 1
'r': 2
's': 1
'u': 1


### Problem 11: Text Cleaning - Remove Numbers and Extra Spaces (Regex)

**Task:** Write a function that uses regular expressions to perform two cleaning steps on a text:
1.  Remove all digits (0-9).
2.  Replace multiple spaces with a single space.

The function should return the cleaned text.

In [15]:
import re

text = "This text has 123 numbers and   extra   spaces, also 456 digits."

def clean_text(text):
    text = re.sub(r'\d+', '', text)       # Remove digits
    text = re.sub(r' +', ' ', text)       # Multiple spaces → single space
    return text.strip()

print(clean_text(text))


This text has numbers and extra spaces, also digits.


### Problem 12: Average Sentence Length (NLTK)

**Task:** Calculate the average word count per sentence in a given paragraph using NLTK's `sent_tokenize` and `word_tokenize`. Print the average length.

In [16]:
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download('punkt')

paragraph = "NLP is amazing. It helps machines understand human language. This is a very interesting field of study and has many applications."

sentences = sent_tokenize(paragraph)
total_words = sum(len(word_tokenize(s)) for s in sentences)
avg_length = total_words / len(sentences)

print(f"Number of sentences: {len(sentences)}")
print(f"Average sentence length: {avg_length:.2f} words")

Number of sentences: 3
Average sentence length: 8.00 words


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


### Problem 13: Enhanced Rule-based Sentiment Analysis

**Task:** Modify the existing `sentiment_analysis` function to include a 'Mixed Sentiment' category. If the text contains both positive and negative words (and neither count is zero), it should be classified as 'Mixed Sentiment'. Otherwise, use the existing 'Positive', 'Negative', or 'Neutral' classifications.

In [17]:
positive_words = {"happy", "good", "great", "excellent", "love", "amazing"}
negative_words = {"sad", "bad", "terrible", "hate", "awful", "worst"}

def sentiment_analysis_enhanced(text):
    words = text.lower().split()
    pos_count = sum(1 for w in words if w.strip(".,!?") in positive_words)
    neg_count = sum(1 for w in words if w.strip(".,!?") in negative_words)

    if pos_count > 0 and neg_count > 0:
        return "Mixed Sentiment"
    elif pos_count > 0:
        return "Positive"
    elif neg_count > 0:
        return "Negative"
    else:
        return "Neutral"

text1 = "I love this product, but the delivery was terrible."
text2 = "This is a great movie."
text3 = "The service was awful."
text4 = "It was okay."

print(f"Text 1 Sentiment: {sentiment_analysis_enhanced(text1)}")  # Mixed
print(f"Text 2 Sentiment: {sentiment_analysis_enhanced(text2)}")  # Positive
print(f"Text 3 Sentiment: {sentiment_analysis_enhanced(text3)}")  # Negative
print(f"Text 4 Sentiment: {sentiment_analysis_enhanced(text4)}")  # Neutral

Text 1 Sentiment: Mixed Sentiment
Text 2 Sentiment: Positive
Text 3 Sentiment: Negative
Text 4 Sentiment: Neutral



### Problem 14: Bag-of-Words Representation for a New Corpus

**Task:** Apply `CountVectorizer` to the new corpus provided. Print the feature names (vocabulary) and the Bag-of-Words (BoW) representation (as an array) for each document in the corpus.

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

new_corpus = [
    "Machine learning is a fascinating field",
    "Deep learning is a subset of machine learning and uses neural networks",
    "Neural networks are powerful tools for AI"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(new_corpus)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("\nBoW Matrix:\n", X.toarray())

Vocabulary: ['ai' 'and' 'are' 'deep' 'fascinating' 'field' 'for' 'is' 'learning'
 'machine' 'networks' 'neural' 'of' 'powerful' 'subset' 'tools' 'uses']

BoW Matrix:
 [[0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 1 2 1 1 1 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0]]


### Problem 15: TF-IDF and Top 3 Keywords per Document

**Task:** Apply `TfidfVectorizer` to the provided corpus. Then, for each document, identify and print the top 3 most important keywords based on their TF-IDF scores.

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

corpus_for_tfidf = [
    "The cat sat on the mat and purred happily",
    "A small dog ran in the park chasing a ball",
    "Cats and dogs are common pets and can be very playful"
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus_for_tfidf)
feature_names = vectorizer.get_feature_names_out()

for i, row in enumerate(X.toarray()):
    top3_indices = np.argsort(row)[::-1][:3]
    top3_keywords = [(feature_names[j], round(row[j], 4)) for j in top3_indices]
    print(f"Doc {i+1}: {top3_keywords}")

Doc 1: [('the', np.float64(0.5101)), ('sat', np.float64(0.3354)), ('purred', np.float64(0.3354))]
Doc 2: [('small', np.float64(0.3633)), ('ran', np.float64(0.3633)), ('in', np.float64(0.3633))]
Doc 3: [('and', np.float64(0.4522)), ('very', np.float64(0.2973)), ('playful', np.float64(0.2973))]
